/*
  Warnings:

  - The values [RECURRING_INVOICE_CREATED,RECURRING_INVOICE_UPDATED,RECURRING_INVOICE_DELETED,RECURRING_INVOICE_GENERATED,RECURRING_INVOICE_AUTO_SENT,RECURRING_INVOICE_PROCESSED,RECURRING_INVOICE_NEXT_DATE_CALCULATED,RECURRING_INVOICE_ITEM_CREATED,RECURRING_INVOICE_ITEM_UPDATED,RECURRING_INVOICE_ITEM_DELETED] on the enum `WebhookEvent` will be removed. If these variants are still used in the database, this will fail.
  - You are about to drop the column `recurringInvoiceId` on the `Invoice` table. All the data in the column will be lost.
  - You are about to drop the `RecurringInvoice` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `RecurringInvoiceItem` table. If the table is not empty, all the data it contains will be lost.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "WebhookEvent_new" AS ENUM ('QUOTE_CREATED', 'QUOTE_UPDATED', 'QUOTE_DELETED', 'QUOTE_SENT', 'QUOTE_SIGNED', 'QUOTE_EXPIRED', 'QUOTE_REJECTED', 'QUOTE_VIEWED', 'QUOTE_MARKED_AS_SIGNED', 'QUOTE_PDF_GENERATED', 'QUOTE_SEARCHED', 'QUOTE_STATUS_CHANGED', 'INVOICE_CREATED', 'INVOICE_UPDATED', 'INVOICE_DELETED', 'INVOICE_SENT', 'INVOICE_PAID', 'INVOICE_OVERDUE', 'INVOICE_MARKED_AS_PAID', 'INVOICE_PDF_GENERATED', 'INVOICE_XML_DOWNLOADED', 'INVOICE_CREATED_FROM_QUOTE', 'INVOICE_SEARCHED', 'INVOICE_STATUS_CHANGED', 'RECEIPT_CREATED', 'RECEIPT_UPDATED', 'RECEIPT_DELETED', 'RECEIPT_SENT', 'RECEIPT_PDF_GENERATED', 'RECEIPT_CREATED_FROM_INVOICE', 'RECEIPT_SEARCHED', 'PAYMENT_RECEIVED', 'PAYMENT_METHOD_CREATED', 'PAYMENT_METHOD_UPDATED', 'PAYMENT_METHOD_DELETED', 'PAYMENT_METHOD_ACTIVATED', 'PAYMENT_METHOD_DEACTIVATED', 'SIGNATURE_CREATED', 'SIGNATURE_COMPLETED', 'SIGNATURE_EXPIRED', 'SIGNATURE_OTP_GENERATED', 'SIGNATURE_OTP_SENT', 'SIGNATURE_VIEWED', 'SIGNATURE_EMAIL_SENT', 'CLIENT_CREATED', 'CLIENT_UPDATED', 'CLIENT_DELETED', 'CLIENT_ACTIVATED', 'CLIENT_DEACTIVATED', 'CLIENT_SEARCHED', 'COMPANY_CREATED', 'COMPANY_UPDATED', 'COMPANY_PDF_CONFIG_UPDATED', 'COMPANY_EMAIL_TEMPLATE_UPDATED', 'COMPANY_INFO_VIEWED', 'PLUGIN_ACTIVATED', 'PLUGIN_DEACTIVATED', 'PLUGIN_CONFIGURED', 'PLUGIN_ADDED', 'PLUGIN_REMOVED', 'PLUGIN_VALIDATED', 'PLUGIN_PROVIDER_REQUESTED', 'PLUGIN_FORMAT_REQUESTED', 'PLUGIN_WEBHOOK_RECEIVED', 'USER_CREATED', 'USER_UPDATED', 'USER_LOGGED_IN', 'USER_PASSWORD_CHANGED', 'USER_PROFILE_UPDATED', 'USER_OIDC_LOGIN', 'USER_OIDC_CALLBACK', 'EMAIL_SENT', 'EMAIL_TEMPLATE_UPDATED', 'EMAIL_FAILED', 'DASHBOARD_VIEWED', 'DASHBOARD_STATS_CALCULATED', 'STATS_MONTHLY_REQUESTED', 'STATS_YEARLY_REQUESTED', 'CURRENCY_RATE_UPDATED', 'APP_RESET', 'APP_ALL_DATA_RESET', 'OTP_REQUESTED', 'OTP_VALIDATED', 'OTP_EXPIRED', 'SEARCH_PERFORMED', 'PDF_GENERATED', 'XML_GENERATED', 'FILE_DOWNLOADED', 'WEBHOOK_CREATED', 'WEBHOOK_UPDATED', 'WEBHOOK_DELETED', 'WEBHOOK_TRIGGERED', 'WEBHOOK_FAILED', 'QUOTE_ITEM_CREATED', 'QUOTE_ITEM_UPDATED', 'QUOTE_ITEM_DELETED', 'INVOICE_ITEM_CREATED', 'INVOICE_ITEM_UPDATED', 'INVOICE_ITEM_DELETED', 'RECEIPT_ITEM_CREATED', 'RECEIPT_ITEM_UPDATED', 'RECEIPT_ITEM_DELETED', 'PDF_CONFIG_CREATED', 'PDF_CONFIG_UPDATED', 'EMAIL_TEMPLATE_CREATED', 'QUOTE_NUMBER_GENERATED', 'INVOICE_NUMBER_GENERATED', 'RECEIPT_NUMBER_GENERATED', 'CRON_JOB_STARTED', 'CRON_JOB_COMPLETED', 'CRON_JOB_FAILED', 'CURRENCY_CONVERSION_REQUESTED', 'CURRENCY_RATE_FETCHED', 'MAIL_TEMPLATE_CREATED', 'MAIL_TEMPLATE_UPDATED', 'SSE_CONNECTION_ESTABLISHED', 'SSE_DATA_STREAMED', 'DATA_VALIDATED', 'CONFIGURATION_VALIDATED');
ALTER TABLE "Webhook" ALTER COLUMN "events" TYPE "WebhookEvent_new"[] USING ("events"::text::"WebhookEvent_new"[]);
ALTER TYPE "WebhookEvent" RENAME TO "WebhookEvent_old";
ALTER TYPE "WebhookEvent_new" RENAME TO "WebhookEvent";
DROP TYPE "public"."WebhookEvent_old";
COMMIT;

-- DropForeignKey
ALTER TABLE "Invoice" DROP CONSTRAINT "Invoice_recurringInvoiceId_fkey";

-- DropForeignKey
ALTER TABLE "RecurringInvoice" DROP CONSTRAINT "RecurringInvoice_clientId_fkey";

-- DropForeignKey
ALTER TABLE "RecurringInvoice" DROP CONSTRAINT "RecurringInvoice_companyId_fkey";

-- DropForeignKey
ALTER TABLE "RecurringInvoiceItem" DROP CONSTRAINT "RecurringInvoiceItem_recurringInvoiceId_fkey";

-- AlterTable
ALTER TABLE "Invoice" DROP COLUMN "recurringInvoiceId";

-- DropTable
DROP TABLE "RecurringInvoice";

-- DropTable
DROP TABLE "RecurringInvoiceItem";
