/**
 * peppol.sh adapter unit tests — mocked HTTP layer.
 *
 * Endpoint paths, payload field names and the status enum below mirror the REAL API
 * (verified live against https://api.peppol.sh/v1/openapi.json + a real sandbox
 * round-trip on 2026-07-11 — including the two undocumented behaviours: ps_test_ keys
 * only work on sandbox.peppol.sh, and GET /v1/documents/{id} requires ?company_id=).
 *
 * LIVE PROOF: peppol-sh-live.spec.ts (PEPPOL_LIVE=1 PEPPOL_AP_PROVIDER=peppol-sh) —
 * zero-secret self-signup, so the mocked suite here is never the only line of defence.
 *
 * The UBL fed to the extractor is generated by our real EN16931 UBL builder
 * (InvoiceRenderingService.buildEInvoice) — no hand-written XML.
 */
import {
  InvoiceRenderingService,
  InvoiceRenderData,
} from '../../../../modules/invoice-rendering/invoice-rendering.service';
import { PEPPOL_BILLING_PROCESS_ID, PEPPOL_DOC_TYPES } from './peppol-client';
import {
  PEPPOL_SH_PROD_URL,
  PEPPOL_SH_SANDBOX_URL,
  PeppolShApClient,
  ublToPeppolShDocument,
} from './peppol-sh-client';

// ---------------------------------------------------------------------------
// Mock fetch
// ---------------------------------------------------------------------------

const mockFetch = jest.fn() as jest.MockedFunction<typeof fetch>;
global.fetch = mockFetch as unknown as typeof fetch;

beforeEach(() => {
  mockFetch.mockReset();
});

function mockJsonResponse(body: unknown, status = 200): Response {
  return {
    ok: status >= 200 && status < 300,
    status,
    json: async () => body,
    text: async () => JSON.stringify(body),
  } as unknown as Response;
}

// ---------------------------------------------------------------------------
// UBL fixture — generated with the real builder (no hand-written XML)
// ---------------------------------------------------------------------------

const NOW = new Date('2026-07-01T10:00:00Z');

function renderData(): InvoiceRenderData {
  return {
    rawNumber: 'INV-PSH-001',
    number: null,
    issuedAt: NOW,
    createdAt: NOW,
    company: {
      name: 'Seller SAS',
      description: null,
      foundedAt: null,
      currency: 'EUR',
      address: '1 Rue de Test',
      city: 'Paris',
      postalCode: '75001',
      country: 'France',
      email: 'seller@example.com',
      partyIdentifiers: [{ scheme: 'VAT', value: 'FR32123456789' }],
    },
    client: {
      type: 'COMPANY',
      name: 'Buyer GmbH',
      description: null,
      foundedAt: null,
      contactFirstname: null,
      contactLastname: null,
      contactEmail: 'buyer@example.com',
      salutation: null,
      sex: null,
      title: null,
      isActive: true,
      address: 'Käuferstr. 2',
      city: 'Munich',
      postalCode: '80333',
      country: 'Germany',
      partyIdentifiers: [{ scheme: 'VAT', value: 'DE811907980' }],
    },
    items: [
      { name: 'Consulting', quantity: 10, unitPrice: 100, vatRate: 19, vatCategory: 'S', type: 'SERVICE' },
      { name: 'Licence', quantity: 2, unitPrice: 50, vatRate: 19, vatCategory: 'S', type: 'PRODUCT' },
    ],
  } as InvoiceRenderData;
}

let ublXml: string;

beforeAll(async () => {
  const service = new InvoiceRenderingService();
  ublXml = await service.buildEInvoice(renderData()).exportXml('ubl');
});

const CONFIG = {
  apiKey: 'ps_test_unit_key',
  companyId: 'com_unit_test',
  environment: 'TEST' as const,
};

function sendRequest(overrides: Partial<Parameters<PeppolShApClient['send']>[0]> = {}) {
  return {
    senderParticipantId: '9957:FR32123456789',
    receiverParticipantId: '9930:DE811907980',
    documentTypeId: PEPPOL_DOC_TYPES.INVOICE_UBL,
    processId: PEPPOL_BILLING_PROCESS_ID,
    documentBytes: Buffer.from(ublXml, 'utf-8'),
    idempotencyKey: 'unit-key-1',
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// ublToPeppolShDocument — UBL → JSON extraction
// ---------------------------------------------------------------------------

describe('ublToPeppolShDocument', () => {
  it('extracts number, dates, currency, parties and lines from our generated UBL', () => {
    const payload = ublToPeppolShDocument(ublXml);

    expect(payload.type).toBe('invoice');
    expect(payload.number).toBe('INV-PSH-001');
    expect(payload.issue_date).toBe('2026-07-01');
    expect(payload.currency).toBe('EUR');

    expect(payload.from).toEqual({ name: 'Seller SAS', tax_id: 'FR32123456789' });
    expect(payload.to).toEqual({ name: 'Buyer GmbH', tax_id: 'DE811907980' });

    expect(payload.lines).toHaveLength(2);
    expect(payload.lines[0]).toMatchObject({
      description: 'Consulting',
      quantity: 10,
      unit_price: 100,
      tax_rate: 19,
    });
    expect(payload.lines[1]).toMatchObject({
      description: 'Licence',
      quantity: 2,
      unit_price: 50,
      tax_rate: 19,
    });
  });

  it('throws a descriptive error when the buyer has no tax ID', async () => {
    const data = renderData();
    data.client.partyIdentifiers = [];
    const xml = await new InvoiceRenderingService().buildEInvoice(data).exportXml('ubl');

    expect(() => ublToPeppolShDocument(xml)).toThrow(/AccountingCustomerParty.*tax ID/);
  });

  it('rejects non-UBL documents', () => {
    expect(() => ublToPeppolShDocument('<CrossIndustryInvoice/>')).toThrow(/unsupported UBL root element/);
  });
});

// ---------------------------------------------------------------------------
// send()
// ---------------------------------------------------------------------------

describe('PeppolShApClient.send', () => {
  it('POSTs the JSON document to {sandbox}/v1/documents with Bearer auth (TEST env)', async () => {
    mockFetch.mockResolvedValueOnce(
      mockJsonResponse({ id: 'doc_abc123', status: 'queued', url: '/v1/documents/doc_abc123' }, 202),
    );

    const client = new PeppolShApClient(CONFIG);
    const result = await client.send(sendRequest());

    expect(result).toEqual({ messageId: 'doc_abc123', status: 'QUEUED' });

    const [url, opts] = mockFetch.mock.calls[0] as [string, RequestInit];
    expect(url).toBe(`${PEPPOL_SH_SANDBOX_URL}/v1/documents`);
    expect(opts.method).toBe('POST');
    expect((opts.headers as Record<string, string>).Authorization).toBe('Bearer ps_test_unit_key');

    const body = JSON.parse(opts.body as string);
    expect(body.company_id).toBe('com_unit_test');
    expect(body.type).toBe('invoice');
    expect(body.number).toBe('INV-PSH-001');
    expect(body.issue_date).toBe('2026-07-01');
    expect(body.currency).toBe('EUR');
    expect(body.from).toEqual({ name: 'Seller SAS', tax_id: 'FR32123456789' });
    // Explicit receiver Peppol ID overrides peppol.sh's tax_id lookup.
    expect(body.to).toEqual({
      name: 'Buyer GmbH',
      tax_id: 'DE811907980',
      peppol_id: '9930:DE811907980',
    });
    expect(body.lines).toHaveLength(2);
    expect(body.idempotency_key).toBe('unit-key-1');
  });

  it('targets api.peppol.sh in PROD environment', async () => {
    mockFetch.mockResolvedValueOnce(mockJsonResponse({ id: 'doc_prod1', status: 'queued' }, 202));

    const client = new PeppolShApClient({ ...CONFIG, environment: 'PROD' });
    await client.send(sendRequest());

    const [url] = mockFetch.mock.calls[0] as [string];
    expect(url).toBe(`${PEPPOL_SH_PROD_URL}/v1/documents`);
  });

  it('omits to.peppol_id when no receiver participant id (tax_id routing)', async () => {
    mockFetch.mockResolvedValueOnce(mockJsonResponse({ id: 'doc_x', status: 'queued' }, 202));

    const client = new PeppolShApClient(CONFIG);
    await client.send(sendRequest({ receiverParticipantId: '' }));

    const body = JSON.parse((mockFetch.mock.calls[0] as [string, RequestInit])[1].body as string);
    expect(body.to.peppol_id).toBeUndefined();
    expect(body.to.tax_id).toBe('DE811907980');
  });

  it('throws with the canonical error envelope on non-2xx (consistent with other channels)', async () => {
    mockFetch.mockResolvedValueOnce(
      mockJsonResponse(
        {
          error: {
            type: 'billing_error',
            code: 'insufficient_credits',
            message: 'Company does not have enough credits',
          },
        },
        402,
      ),
    );

    const client = new PeppolShApClient(CONFIG);
    await expect(client.send(sendRequest())).rejects.toThrow(
      /peppol\.sh send failed: HTTP 402 — insufficient_credits/,
    );
  });
});

// ---------------------------------------------------------------------------
// getStatus()
// ---------------------------------------------------------------------------

describe('PeppolShApClient.getStatus', () => {
  it.each([
    ['queued', 'QUEUED'],
    ['sending', 'SENT'],
    ['delivered', 'DELIVERED'],
    ['failed', 'FAILED'],
    ['weird', 'UNKNOWN'],
  ])('maps %s → %s', async (raw, expected) => {
    mockFetch.mockResolvedValueOnce(mockJsonResponse({ id: 'doc_abc123', status: raw }));

    const client = new PeppolShApClient(CONFIG);
    const result = await client.getStatus('doc_abc123');

    expect(result.status).toBe(expected);
    expect(result.messageId).toBe('doc_abc123');
  });

  it('includes the required company_id query parameter (verified live: 400 without)', async () => {
    mockFetch.mockResolvedValueOnce(mockJsonResponse({ id: 'doc_abc123', status: 'delivered' }));

    const client = new PeppolShApClient(CONFIG);
    await client.getStatus('doc_abc123');

    const [url] = mockFetch.mock.calls[0] as [string];
    expect(url).toBe(`${PEPPOL_SH_SANDBOX_URL}/v1/documents/doc_abc123?company_id=com_unit_test`);
  });

  it('surfaces the last event message on failed documents', async () => {
    mockFetch.mockResolvedValueOnce(
      mockJsonResponse({
        id: 'doc_bad',
        status: 'failed',
        events: [
          { type: 'queued', message: 'accepted' },
          { type: 'failed', message: 'participant not registered' },
        ],
      }),
    );

    const client = new PeppolShApClient(CONFIG);
    const result = await client.getStatus('doc_bad');

    expect(result.status).toBe('FAILED');
    expect(result.mlrDescription).toBe('participant not registered');
  });
});

// ---------------------------------------------------------------------------
// sendInvoiceResponse() + bootstrap helpers
// ---------------------------------------------------------------------------

describe('PeppolShApClient — invoice response + bootstrap', () => {
  it('sendInvoiceResponse throws (no ApplicationResponse endpoint in the peppol.sh API)', async () => {
    const client = new PeppolShApClient(CONFIG);
    await expect(
      client.sendInvoiceResponse({
        senderParticipantId: '9930:DE811907980',
        receiverParticipantId: '9957:FR32123456789',
        originalMessageId: 'doc_abc123',
        responseCode: 'AB',
      }),
    ).rejects.toThrow(/does not support sending Peppol Invoice Responses/);
    expect(mockFetch).not.toHaveBeenCalled();
  });

  it('signup POSTs to the public endpoint on the production host and returns the one-time key', async () => {
    mockFetch.mockResolvedValueOnce(
      mockJsonResponse(
        { id: 'acc_123', email: 'a@b.c', status: 'active', api_key: 'ps_test_generated' },
        201,
      ),
    );

    const result = await PeppolShApClient.signup('a@b.c', 'Unit');

    expect(result).toEqual({ accountId: 'acc_123', apiKey: 'ps_test_generated' });
    const [url, opts] = mockFetch.mock.calls[0] as [string, RequestInit];
    expect(url).toBe(`${PEPPOL_SH_PROD_URL}/v1/signup`);
    expect(JSON.parse(opts.body as string)).toEqual({ email: 'a@b.c', name: 'Unit' });
    // Public endpoint — no Authorization header.
    expect((opts.headers as Record<string, string>).Authorization).toBeUndefined();
  });

  it('createCompany POSTs to the sandbox host by default and returns the com_ id', async () => {
    mockFetch.mockResolvedValueOnce(mockJsonResponse({ id: 'com_created', name: 'Unit Co' }, 201));

    const result = await PeppolShApClient.createCompany('ps_test_generated', {
      name: 'Unit Co',
      taxId: 'FR32123456789',
      country: 'FR',
    });

    expect(result).toEqual({ companyId: 'com_created' });
    const [url, opts] = mockFetch.mock.calls[0] as [string, RequestInit];
    expect(url).toBe(`${PEPPOL_SH_SANDBOX_URL}/v1/companies`);
    expect((opts.headers as Record<string, string>).Authorization).toBe('Bearer ps_test_generated');
    expect(JSON.parse(opts.body as string)).toEqual({
      name: 'Unit Co',
      tax_id: 'FR32123456789',
      country: 'FR',
    });
  });
});
