export const countryToCurrency: Record<string, string> = {
  // Europe - EUR
  "Austria": "EUR",
  "Belgium": "EUR",
  "Croatia": "EUR",
  "Cyprus": "EUR",
  "Czechia": "EUR",
  "Estonia": "EUR",
  "Finland": "EUR",
  "France": "EUR",
  "Germany": "EUR",
  "Greece": "EUR",
  "Hungary": "EUR",
  "Ireland": "EUR",
  "Italy": "EUR",
  "Latvia": "EUR",
  "Lithuania": "EUR",
  "Luxembourg": "EUR",
  "Malta": "EUR",
  "Netherlands": "EUR",
  "Poland": "EUR",
  "Portugal": "EUR",
  "Romania": "EUR",
  "Slovakia": "EUR",
  "Slovenia": "EUR",
  "Spain": "EUR",

  // Europe - Other
  "United Kingdom": "GBP",
  "Switzerland": "CHF",
  "Norway": "NOK",
  "Sweden": "SEK",
  "Denmark": "DKK",
  "Iceland": "ISK",
  "Russia": "RUB",
  "Turkey": "TRY",
  "Ukraine": "UAH",

  // Americas - North
  "Canada": "CAD",
  "United States": "USD",
  "Mexico": "MXN",

  // Americas - Central & Caribbean
  "Belize": "BZD",
  "Costa Rica": "CRC",
  "Dominican Republic": "DOP",
  "El Salvador": "USD",
  "Guatemala": "GTQ",
  "Haiti": "HTG",
  "Honduras": "HNL",
  "Jamaica": "JMD",
  "Nicaragua": "NIO",
  "Panama": "PAB",
  "Trinidad and Tobago": "TTD",

  // Americas - South
  "Argentina": "ARS",
  "Bolivia": "BOB",
  "Brazil": "BRL",
  "Chile": "CLP",
  "Colombia": "COP",
  "Ecuador": "USD",
  "Guyana": "GYD",
  "Paraguay": "PYG",
  "Peru": "PEN",
  "Suriname": "SRD",
  "Uruguay": "UYU",
  "Venezuela": "VES",

  // Middle East & North Africa
  "Bahrain": "BHD",
  "Egypt": "EGP",
  "Iran": "IRR",
  "Iraq": "IQD",
  "Israel": "ILS",
  "Jordan": "JOD",
  "Kuwait": "KWD",
  "Lebanon": "LBP",
  "Libya": "LYD",
  "Morocco": "MAD",
  "Oman": "OMR",
  "Qatar": "QAR",
  "Saudi Arabia": "SAR",
  "Syria": "SYP",
  "Tunisia": "TND",
  "United Arab Emirates": "AED",
  "Yemen": "YER",

  // South Asia
  "Afghanistan": "AFN",
  "Bangladesh": "BDT",
  "Bhutan": "BTN",
  "India": "INR",
  "Maldives": "MVR",
  "Nepal": "NPR",
  "Pakistan": "PKR",
  "Sri Lanka": "LKR",

  // East & Southeast Asia
  "Cambodia": "KHR",
  "China": "CNY",
  "Hong Kong": "HKD",
  "Indonesia": "IDR",
  "Japan": "JPY",
  "Laos": "LAK",
  "Macao": "MOP",
  "Malaysia": "MYR",
  "Mongolia": "MNT",
  "Myanmar": "MMK",
  "Philippines": "PHP",
  "Singapore": "SGD",
  "South Korea": "KRW",
  "Taiwan": "TWD",
  "Thailand": "THB",
  "Timor-Leste": "USD",
  "Vietnam": "VND",

  // Oceania
  "Australia": "AUD",
  "Fiji": "FJD",
  "Kiribati": "AUD",
  "Marshall Islands": "USD",
  "Micronesia": "USD",
  "Nauru": "AUD",
  "New Zealand": "NZD",
  "Palau": "USD",
  "Papua New Guinea": "PGK",
  "Samoa": "WST",
  "Solomon Islands": "SBD",
  "Tonga": "TOP",
  "Tuvalu": "AUD",
  "Vanuatu": "VUV",

  // Africa - North & Central
  "Algeria": "DZD",
  "Angola": "AOA",
  "Benin": "XOF",
  "Botswana": "BWP",
  "Burkina Faso": "XOF",
  "Burundi": "BIF",
  "Cameroon": "XAF",
  "Central African Republic": "XAF",
  "Chad": "XAF",
  "Comoros": "KMF",
  "Côte d'Ivoire": "XOF",
  "Congo": "XAF",
  "Democratic Republic of the Congo": "CDF",
  "Djibouti": "DJF",
  "Equatorial Guinea": "XAF",
  "Eritrea": "ERN",
  "Eswatini": "SZL",
  "Ethiopia": "ETB",
  "Gabon": "XAF",
  "Gambia": "GMD",
  "Ghana": "GHS",
  "Guinea": "GNF",
  "Guinea-Bissau": "XOF",
  "Kenya": "KES",
  "Lesotho": "LSL",
  "Liberia": "LRD",
  "Madagascar": "MGA",
  "Malawi": "MWK",
  "Mali": "XOF",
  "Mauritania": "MRU",
  "Mauritius": "MUR",
  "Mozambique": "MZN",
  "Namibia": "NAD",
  "Niger": "XOF",
  "Nigeria": "NGN",
  "Rwanda": "RWF",
  "Senegal": "XOF",
  "Seychelles": "SCR",
  "Sierra Leone": "SLL",
  "Somalia": "SOS",
  "South Africa": "ZAR",
  "South Sudan": "SSP",
  "Sudan": "SDG",
  "Tanzania": "TZS",
  "Togo": "XOF",
  "Uganda": "UGX",
  "Zambia": "ZMW",
  "Zimbabwe": "ZWL",

  // Caucasus & Central Asia
  "Armenia": "AMD",
  "Azerbaijan": "AZN",
  "Georgia": "GEL",
  "Kazakhstan": "KZT",
  "Kyrgyzstan": "KGS",
  "Tajikistan": "TJS",
  "Turkmenistan": "TMT",
  "Uzbekistan": "UZS",
}
