const COUNTRY_MAP: Record<string, string> = {
	// ISO codes passthrough
	FR: "FR",
	DE: "DE",
	US: "US",
	GB: "GB",
	ES: "ES",
	IT: "IT",
	BE: "BE",
	CH: "CH",
	CA: "CA",
	NL: "NL",
	LU: "LU",
	AT: "AT",
	PT: "PT",
	IE: "IE",
	DK: "DK",
	SE: "SE",
	FI: "FI",
	PL: "PL",
	CZ: "CZ",
	SK: "SK",
	HU: "HU",
	RO: "RO",
	BG: "BG",
	GR: "GR",
	HR: "HR",
	SI: "SI",
	LT: "LT",
	LV: "LV",
	EE: "EE",
	CY: "CY",
	MT: "MT",
	NO: "NO",
	JP: "JP",
	AU: "AU",
	NZ: "NZ",
	SG: "SG",
	CN: "CN",
	IN: "IN",
	BR: "BR",
	MX: "MX",
	AE: "AE",
	SA: "SA",
	ZA: "ZA",
	RU: "RU",
	AR: "AR",
	CL: "CL",
	CO: "CO",
	IL: "IL",
	TR: "TR",
	KR: "KR",
	ID: "ID",
	MY: "MY",
	TH: "TH",
	VN: "VN",
	PH: "PH",
	TW: "TW",
	HK: "HK",
	MA: "MA",
	DZ: "DZ",
	TN: "TN",
	NG: "NG",
	KE: "KE",
	GH: "GH",
	EG: "EG",
	PE: "PE",
	UA: "UA",
	MC: "MC",
	LI: "LI",
	SM: "SM",
	VA: "VA",
	AD: "AD",
	IS: "IS",
	UK: "GB",
	EL: "GR",
	// 3-letter ISO codes
	FRA: "FR",
	DEU: "DE",
	USA: "US",
	GBR: "GB",
	ESP: "ES",
	ITA: "IT",
	BEL: "BE",
	CHE: "CH",
	CAN: "CA",
	NLD: "NL",
	LUX: "LU",
	AUT: "AT",
	PRT: "PT",
	IRL: "IE",
	DNK: "DK",
	SWE: "SE",
	FIN: "FI",
	POL: "PL",
	CZE: "CZ",
	SVK: "SK",
	HUN: "HU",
	ROU: "RO",
	BGR: "BG",
	GRC: "GR",
	HRV: "HR",
	SVN: "SI",
	LTU: "LT",
	LVA: "LV",
	EST: "EE",
	CYP: "CY",
	MLT: "MT",
	NOR: "NO",
	JPN: "JP",
	AUS: "AU",
	NZL: "NZ",
	SGP: "SG",
	CHN: "CN",
	IND: "IN",
	BRA: "BR",
	MEX: "MX",
	ARE: "AE",
	UAE: "AE",
	SAU: "SA",
	ZAF: "ZA",
	RUS: "RU",
	ARG: "AR",
	CHL: "CL",
	COL: "CO",
	ISR: "IL",
	TUR: "TR",
	KOR: "KR",
	IDN: "ID",
	MYS: "MY",
	THA: "TH",
	VNM: "VN",
	PHL: "PH",
	TWN: "TW",
	HKG: "HK",
	MAR: "MA",
	DZA: "DZ",
	TUN: "TN",
	NGA: "NG",
	KEN: "KE",
	GHA: "GH",
	EGY: "EG",
	PER: "PE",
	UKR: "UA",
	MCO: "MC",
	LIE: "LI",
	SMR: "SM",
	VAT: "VA",
	AND: "AD",
	ISL: "IS",

	// English names
	FRANCE: "FR",
	GERMANY: "DE",
	"UNITED STATES": "US",
	"UNITED STATES OF AMERICA": "US",
	"UNITED KINGDOM": "GB",
	SPAIN: "ES",
	ITALY: "IT",
	BELGIUM: "BE",
	SWITZERLAND: "CH",
	CANADA: "CA",
	NETHERLANDS: "NL",
	LUXEMBOURG: "LU",
	AUSTRIA: "AT",
	PORTUGAL: "PT",
	IRELAND: "IE",
	DENMARK: "DK",
	SWEDEN: "SE",
	FINLAND: "FI",
	POLAND: "PL",
	"CZECH REPUBLIC": "CZ",
	CZECHIA: "CZ",
	SLOVAKIA: "SK",
	HUNGARY: "HU",
	ROMANIA: "RO",
	BULGARIA: "BG",
	GREECE: "GR",
	CROATIA: "HR",
	SLOVENIA: "SI",
	LITHUANIA: "LT",
	LATVIA: "LV",
	ESTONIA: "EE",
	CYPRUS: "CY",
	MALTA: "MT",
	NORWAY: "NO",
	JAPAN: "JP",
	AUSTRALIA: "AU",
	"NEW ZEALAND": "NZ",
	SINGAPORE: "SG",
	CHINA: "CN",
	INDIA: "IN",
	BRAZIL: "BR",
	MEXICO: "MX",
	"UNITED ARAB EMIRATES": "AE",
	"SAUDI ARABIA": "SA",
	"SOUTH AFRICA": "ZA",
	RUSSIA: "RU",
	ARGENTINA: "AR",
	CHILE: "CL",
	COLOMBIA: "CO",
	ISRAEL: "IL",
	TURKEY: "TR",
	"SOUTH KOREA": "KR",
	INDONESIA: "ID",
	MALAYSIA: "MY",
	THAILAND: "TH",
	VIETNAM: "VN",
	PHILIPPINES: "PH",
	TAIWAN: "TW",
	"HONG KONG": "HK",
	MOROCCO: "MA",
	ALGERIA: "DZ",
	TUNISIA: "TN",
	NIGERIA: "NG",
	KENYA: "KE",
	GHANA: "GH",
	EGYPT: "EG",
	PERU: "PE",
	UKRAINE: "UA",
	MONACO: "MC",
	LIECHTENSTEIN: "LI",
	"SAN MARINO": "SM",
	VATICAN: "VA",
	ANDORRA: "AD",
	ICELAND: "IS",

	// French names
	ALLEMAGNE: "DE",
	"ÉTATS-UNIS": "US",
	"ETATS-UNIS": "US",
	"ÉTATS-UNIS D'AMÉRIQUE": "US",
	"ETATS-UNIS D AMERIQUE": "US",
	"ROYAUME-UNI": "GB",
	ESPAGNE: "ES",
	ITALIE: "IT",
	BELGIQUE: "BE",
	SUISSE: "CH",
	"PAYS-BAS": "NL",
	AUTRICHE: "AT",
	IRLANDE: "IE",
	DANEMARK: "DK",
	SUÈDE: "SE",
	SUEDE: "SE",
	FINLANDE: "FI",
	POLOGNE: "PL",
	"RÉPUBLIQUE TCHÈQUE": "CZ",
	"REPUBLIQUE TCHEQUE": "CZ",
	SLOVAQUIE: "SK",
	HONGRIE: "HU",
	ROUMANIE: "RO",
	BULGARIE: "BG",
	GRÈCE: "GR",
	GRECE: "GR",
	CROATIE: "HR",
	SLOVÉNIE: "SI",
	SLOVENIE: "SI",
	LITUANIE: "LT",
	LETTONIE: "LV",
	ESTONIE: "EE",
	CHYPRE: "CY",
	MALTE: "MT",
	NORVÈGE: "NO",
	NORVEGE: "NO",
	JAPON: "JP",
	AUSTRALIE: "AU",
	"NOUVELLE-ZÉLANDE": "NZ",
	"NOUVELLE ZELANDE": "NZ",
	SINGAPOUR: "SG",
	CHINE: "CN",
	INDE: "IN",
	BRÉSIL: "BR",
	BRESIL: "BR",
	MEXIQUE: "MX",
	"ÉMIRATS ARABES UNIS": "AE",
	"EMIRATS ARABES UNIS": "AE",
	"ARABIE SAOUDITE": "SA",
	"AFRIQUE DU SUD": "ZA",
	RUSSIE: "RU",
	ARGENTINE: "AR",
	CHILI: "CL",
	COLOMBIE: "CO",
	ISRAËL: "IL",
	TURQUIE: "TR",
	"CORÉE DU SUD": "KR",
	"COREE DU SUD": "KR",
	INDONÉSIE: "ID",
	INDONESIE: "ID",
	MALAISIE: "MY",
	THAÏLANDE: "TH",
	THAILANDE: "TH",
	TAÏWAN: "TW",
};

export function guessCountryCode(freeText: string | null | undefined): string | undefined {
  if (!freeText) return undefined;
  const trimmed = freeText.trim();
  if (!trimmed) return undefined;

  const upper = trimmed.toUpperCase();

  // Check explicit aliases first (covers UK→GB and similar)
  if (COUNTRY_MAP[upper]) return COUNTRY_MAP[upper];

  // If already a 2-letter token not in map, return as-is
  if (/^[A-Z]{2}$/.test(upper)) return upper;

  return undefined;
}
