/**
 * Unit tests for cii-post-process.ts.
 *
 * After the @e-invoice-eu/core migration, all structural injection (SpecifiedLegalOrganization,
 * GlobalID, M1 profile, delivery, EN16931 gaps) is handled by the library at generation time.
 * The post-processor is now a thin namespace normalizer only.
 */
import { normalizeCiiNamespaces, postProcessCiiForCtc } from './cii-post-process';

/** Minimal CII XML with rsm:/ram:/udt: prefixes (as generated by @e-invoice-eu/core). */
const PREFIX_CII = `<?xml version="1.0" encoding="utf-8"?>
<rsm:CrossIndustryInvoice xmlns:rsm="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100" xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100">
  <rsm:ExchangedDocumentContext>
    <ram:BusinessProcessSpecifiedDocumentContextParameter>
      <ram:ID>M1</ram:ID>
    </ram:BusinessProcessSpecifiedDocumentContextParameter>
    <ram:GuidelineSpecifiedDocumentContextParameter>
      <ram:ID>urn:cen.eu:en16931:2017</ram:ID>
    </ram:GuidelineSpecifiedDocumentContextParameter>
  </rsm:ExchangedDocumentContext>
  <rsm:ExchangedDocument>
    <ram:ID>TEST-001</ram:ID>
    <ram:TypeCode>380</ram:TypeCode>
    <ram:IssueDateTime>
      <udt:DateTimeString format="102">20260628</udt:DateTimeString>
    </ram:IssueDateTime>
  </rsm:ExchangedDocument>
  <rsm:SupplyChainTradeTransaction>
    <ram:IncludedSupplyChainTradeLineItem>
      <ram:AssociatedDocumentLineDocument>
        <ram:LineID>1</ram:LineID>
      </ram:AssociatedDocumentLineDocument>
    </ram:IncludedSupplyChainTradeLineItem>
    <ram:ApplicableHeaderTradeAgreement>
      <ram:SellerTradeParty>
        <ram:GlobalID schemeID="0225">000000002</ram:GlobalID>
        <ram:Name>Burger Queen</ram:Name>
        <ram:SpecifiedLegalOrganization>
          <ram:ID schemeID="0002">000000002</ram:ID>
        </ram:SpecifiedLegalOrganization>
      </ram:SellerTradeParty>
      <ram:BuyerTradeParty>
        <ram:GlobalID schemeID="0225">000000001</ram:GlobalID>
        <ram:Name>Tricatel</ram:Name>
        <ram:SpecifiedLegalOrganization>
          <ram:ID schemeID="0002">000000001</ram:ID>
        </ram:SpecifiedLegalOrganization>
        <ram:URIUniversalCommunication>
          <ram:URIID schemeID="0225">000000001</ram:URIID>
        </ram:URIUniversalCommunication>
      </ram:BuyerTradeParty>
    </ram:ApplicableHeaderTradeAgreement>
    <ram:ApplicableHeaderTradeDelivery/>
    <ram:ApplicableHeaderTradeSettlement>
      <ram:InvoiceCurrencyCode>EUR</ram:InvoiceCurrencyCode>
    </ram:ApplicableHeaderTradeSettlement>
  </rsm:SupplyChainTradeTransaction>
</rsm:CrossIndustryInvoice>`;

describe('normalizeCiiNamespaces', () => {
  it('converts rsm:/ram:/udt: prefixes to default xmlns= per element', () => {
    const result = normalizeCiiNamespaces(PREFIX_CII);
    // Root element uses default rsm namespace
    expect(result).toContain('<CrossIndustryInvoice xmlns="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100"');
    // ram: elements use default ram namespace
    expect(result).toContain('<ID xmlns="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100" schemeID="0002">000000002<');
    // Closing tags have no prefix
    expect(result).not.toContain('</rsm:');
    expect(result).not.toContain('</ram:');
    expect(result).not.toContain('</udt:');
    // No opening tags with prefix
    expect(result).not.toContain('<rsm:');
    expect(result).not.toContain('<ram:');
    expect(result).not.toContain('<udt:');
  });

  it('preserves schemeID attributes', () => {
    const result = normalizeCiiNamespaces(PREFIX_CII);
    expect(result).toContain('schemeID="0225">000000002<');
    expect(result).toContain('schemeID="0002">000000002<');
    expect(result).toContain('schemeID="0002">000000001<');
  });

  it('preserves SpecifiedLegalOrganization element', () => {
    const result = normalizeCiiNamespaces(PREFIX_CII);
    expect(result).toContain('SpecifiedLegalOrganization');
    expect(result).toContain('schemeID="0002">000000002<');
  });

  it('preserves M1 profile ID', () => {
    const result = normalizeCiiNamespaces(PREFIX_CII);
    expect(result).toContain('BusinessProcessSpecifiedDocumentContextParameter');
    expect(result).toContain('>M1<');
  });

  it('is idempotent (already-normalized XML is unchanged)', () => {
    const once = normalizeCiiNamespaces(PREFIX_CII);
    const twice = normalizeCiiNamespaces(once);
    expect(once).toBe(twice);
  });

  it('strips namespace prefix declarations from root element', () => {
    const result = normalizeCiiNamespaces(PREFIX_CII);
    expect(result).not.toContain('xmlns:rsm=');
    expect(result).not.toContain('xmlns:ram=');
    expect(result).not.toContain('xmlns:udt=');
  });

  it('preserves CII core structure', () => {
    const result = normalizeCiiNamespaces(PREFIX_CII);
    expect(result).toContain('CrossIndustryInvoice');
    expect(result).toContain('ExchangedDocumentContext');
    expect(result).toContain('ExchangedDocument');
    expect(result).toContain('SupplyChainTradeTransaction');
    expect(result).toContain('ApplicableHeaderTradeAgreement');
    expect(result).toContain('ApplicableHeaderTradeDelivery');
    expect(result).toContain('ApplicableHeaderTradeSettlement');
  });
});

describe('postProcessCiiForCtc', () => {
  it('normalizes namespaces', () => {
    const result = postProcessCiiForCtc(PREFIX_CII);
    expect(result).not.toContain('<ram:');
    expect(result).not.toContain('<rsm:');
    expect(result).toContain('CrossIndustryInvoice');
    expect(result).toContain('SpecifiedLegalOrganization');
    expect(result).toContain('schemeID="0002">000000002<');
  });

  it('replaces seller GlobalID with routing when provided', () => {
    const result = postProcessCiiForCtc(PREFIX_CII, {
      sellerRouting: '315143296_1422',
    });
    // After normalization, the GlobalID value should be the routing, not the SIREN
    expect(result).toContain('315143296_1422');
    // The original SIREN '000000002' should only remain in SpecifiedLegalOrganization (schemeID="0002")
    expect(result).toContain('schemeID="0002">000000002<');
  });

  it('replaces buyer GlobalID with routing when provided', () => {
    const result = postProcessCiiForCtc(PREFIX_CII, {
      buyerRouting: '315143296_1421',
    });
    expect(result).toContain('315143296_1421');
  });

  it('is idempotent (repeated application is stable)', () => {
    const once = postProcessCiiForCtc(PREFIX_CII);
    const twice = postProcessCiiForCtc(once);
    expect(once).toBe(twice);
  });
});
