export {}; // makes this spec a module, not a global script -- see tsconfig.json

/**
 * Receiving invoices — proven THROUGH THE SCREEN, like 17-document-descriptor.cy.ts
 * and the rest of this suite: ACTIONS go through the interface, content ASSERTIONS (is the
 * downloaded file exactly the one uploaded?) go through the API — same conventions as
 * 33-signing-certificates.cy.ts (uploading a real FIXTURE file, never invented data).
 *
 * The detailed lines: a structured deposit now carries
 * ITS OWN LINES (description/quantity/unit price excl. VAT/VAT rate), automatically extracted from
 * the CII/UBL this codebase already knew how to read (`received-invoices/extraction.ts`), and a
 * mismatch between the deposited total and the sum of the lines is a NAMED warning, visible on
 * screen and carried by the document, never blocking (`received-invoices/line-totals-check.ts`).
 *
 * OCR of unstructured PDFs, as a plugin: the "plain PDF" test proves the honest
 * absence of an extractor, and a symmetric test proves that an extractor available via
 * `OCR_SERVICE_URL` pre-fills the form, still editable — both go through a test backend
 * WITHOUT any real OCR engine (`ocr/fake-extractor.ts`, see this file or its own header).
 *
 * Fixtures (`cypress/fixtures/received-invoices/`) — all generated by OUR OWN providers
 * (`cii-provider.ts`/`facturx-provider.ts`), never hand-written XML:
 *  - `supplier-invoice-cii.xml`: real, valid EN 16931 CII. Supplier "Fixture Fournisseur
 *    SARL", no. FIXTURE-INV-0001, date 2026-08-20, EUR, net 750.00 / VAT 150.00 / gross 900.00, ONE
 *    line (3 x 250.00 @ 20%) that sums EXACTLY to these totals — no warning expected.
 *  - `supplier-invoice-facturx.pdf`: a real Factur-X (the same CII, embedded in a real PDF/A-3 via
 *    `@e-invoice-eu/core`) — the human-readable layer of the PDF is a blank placeholder page (a
 *    real Puppeteer render has no place in a fixture generator), but the embedded XML itself is
 *    100% real and was verified offline (extraction.spec.ts) before being committed here.
 *  - `supplier-invoice-plain.pdf`: a real PDF with no embedded XML at all — the case of a craftsman
 *    scanning a paper invoice — so NO line extracted, never a reason for failure.
 *  - `supplier-invoice-ocr-fake.pdf`: NOT a real PDF, DELIBERATELY — a plain
 *    text file carrying the exact marker string of the test OCR stub (`ocr/fake-extractor.ts`,
 *    registered automatically under NODE_ENV=test, never in production); every other "fake" .pdf
 *    extension in this suite (including `supplier-invoice-plain.pdf` above) does NOT carry this
 *    marker and therefore gets the "no extractor available" outcome — exactly the production
 *    default (OCR_SERVICE_URL never configured).
 *  - `supplier-invoice-mismatch.xml`: same method — real CII via `ciiFormatProvider` (one
 *    line, 5 x 100.00 @ 20% = net 500.00 / VAT 100.00 / gross 600.00) — then ONLY the header's own
 *    gross total (`GrandTotalAmount`/`DuePayableAmount`) is surgically bumped to 650.00 afterward:
 *    the real, mundane case of a supplier whose printed total disagrees with their own
 *    lines. Never hand-written XML — a targeted digital edit on a real output.
 *
 * The tests chain in THIS ORDER, on a single `resetAndSeed()` (not one per test — same
 * convention as 17/33): each fixture is therefore genuinely uploaded only ONCE before the
 * test dedicated to the duplicate, which deliberately re-uploads it last.
 *
 * Regression covered by the same pass: 11 (the sidebar/dashboard doesn't break with a 5th type) and
 * 17 (the "received-invoice" descriptor renders its fields and actions like any other —
 * this file needs NO modification for that, it loops over `GET /api/documents/types`).
 */
const api = Cypress.env("apiUrl") || "http://localhost:4000";

const CII_FIXTURE = "cypress/fixtures/received-invoices/supplier-invoice-cii.xml";
const FACTURX_FIXTURE = "cypress/fixtures/received-invoices/supplier-invoice-facturx.pdf";
const PLAIN_PDF_FIXTURE = "cypress/fixtures/received-invoices/supplier-invoice-plain.pdf";
// OCR of unstructured PDFs. This backend's own test double
// (`FakeReceivedInvoiceOcrExtractor`, registered automatically under NODE_ENV=test — see
// `plugins/index.ts`'s own header) only ever answers a document that carries its exact marker
// string in its raw bytes; every OTHER PDF (PLAIN_PDF_FIXTURE included) gets the SAME honest
// "no OCR available" outcome production gets by default (OCR_SERVICE_URL never configured).
const OCR_FAKE_FIXTURE = "cypress/fixtures/received-invoices/supplier-invoice-ocr-fake.pdf";
// Real CII from `ciiFormatProvider` (one line: 5 x 100.00 @ 20% = net 500.00
// / VAT 100.00 / gross 600.00), with ONLY the HEADER's own GrandTotalAmount/DuePayableAmount
// surgically bumped to 650.00 afterwards — the exact, mundane real-world case the warning
// exists to catch (the supplier's own printed total disagrees with what their own lines add up to).
// Never a hand-written fixture: see this file's own header and received-invoices/extraction.spec.ts.
const MISMATCH_FIXTURE = "cypress/fixtures/received-invoices/supplier-invoice-mismatch.xml";

// Supplier matching. Same generation method as every fixture above
// (`ciiFormatProvider`, real EN 16931 CII, never hand-written XML). `KNOWN_VAT_FIXTURE`'s own seller
// carries the SAME VAT (FR12345678901) as the client `createClientByScreen` creates below but a
// DIFFERENT name ("Fixture Fournisseur Reconnu SARL" vs "Fournisseur Confirmé SARL") — the auto-link
// this file proves can therefore only be happening THROUGH THE VAT, never a name coincidence.
// `UNKNOWN_VAT_FIXTURE` shares neither with any client this suite ever creates.
const KNOWN_VAT_FIXTURE = "cypress/fixtures/received-invoices/supplier-invoice-known-vat.xml";
const UNKNOWN_VAT_FIXTURE = "cypress/fixtures/received-invoices/supplier-invoice-unknown-vat.xml";
const SUPPLIER_VAT = "FR12345678901";

interface ReceivedInvoiceInstance {
	id: string;
	status: string;
	data: Record<string, unknown>;
}

function listReceivedInvoices() {
	// GET /api/documents is now a paged `{ items, total, page, pageSize }` — never a bare
	// array (documents.controller.ts's own "List document instances"). `.its("body.items")` loses
	// the element type through Cypress's own dotted-path typing, so this unwraps via `.then` instead
	// to keep every `.find`/`.filter` callback below typed.
	return cy
		.request<{ items: ReceivedInvoiceInstance[] }>({ url: `${api}/api/documents?typeId=received-invoice` })
		.its("body")
		.then((body) => body.items);
}

function uploadAndOpenForm(fixturePath: string) {
	cy.get('[data-cy="received-invoice-upload-button"]').click();
	cy.get('[data-cy="received-invoice-upload-dialog"]', { timeout: 10000 }).should("be.visible");
	cy.get('[data-cy="received-invoice-upload-file-input"]').selectFile(fixturePath, { force: true });
	cy.get('[data-cy="received-invoice-upload-dialog"]').should("not.exist");
	// The dialog (the fixed-position overlay) is what must be visible; the
	// FORM inside it no longer fits above the fold now that it also carries a "lines" row (this is a
	// real, intentional consequence of the new field, not a bug) — `.should("be.visible")` on the
	// whole `<form>` checks its CENTER point, which a taller form can push below the dialog's own
	// scrollable viewport. `exist` is what every subsequent per-field assertion in this file actually
	// depends on; `document-create-dialog`'s own visibility is the genuine "did the dialog open" proof.
	cy.get('[data-cy="document-create-dialog"]', { timeout: 15000 }).should("be.visible");
	cy.get('[data-cy="document-form"]', { timeout: 15000 }).should("exist");
}

/**
 * Reaches the wizard's last step ("Summary", where "receive" — the type's own action — finally
 * renders; every earlier step's primary button reads "Continue" instead, stepped-dialog.tsx) and
 * clicks it. Every received-invoice field is `required: false` (received-invoice.descriptor.ts's
 * own header), so each "Continue" along the way is unconditional — nothing to fill first, unlike
 * document-create-dialog.tsx's own generic wizard-walkers (17-document-descriptor.cy.ts), which
 * exist only because OTHER types DO have required fields. A caller that already navigated to a
 * LATER step for its own field assertions (most of this file does — see each `it`'s own comments)
 * simply arrives here with fewer "Continue" clicks left to make.
 */
function confirmReceive(guard = 0) {
	if (guard > 4) throw new Error("wizard never reached its last step");
	cy.get("body").then(($body) => {
		if ($body.find('[data-cy="document-create-dialog-continue"]').length > 0) {
			cy.continueDocumentWizard();
			confirmReceive(guard + 1);
			return;
		}
		cy.get('[data-cy="document-action-receive"]').click();
		cy.get('[data-sonner-toast]', { timeout: 10000 }).should("exist");
		// A successful first save closes the create dialog and lands on the new record's own page
		// (document-create-dialog.tsx) — the callers below all read the LIST next, so go back to it.
		cy.get('[data-cy="document-create-dialog"]').should("not.exist");
		cy.get('[data-cy="document-detail-page"]', { timeout: 15000 }).should("be.visible");
		cy.visit("/documents/received-invoice");
	});
}

// Creates a client THROUGH THE SCREEN (never seeded/via API): the whole point of
// this screen coverage. Same France + LEGAL_ID(+VAT) pattern already proven in
// 05-clients.cy.ts's own "accepts valid EU VAT format" case.
function createClientByScreen(name: string, opts?: { vat?: string }) {
	cy.visit("/clients");
	cy.contains("button", /add|new|créer|ajouter/i).click();
	cy.get('[data-cy="client-dialog"]', { timeout: 10000 }).should("be.visible");
	cy.get('[name="name"]').clear().type(name);
	cy.continueSteppedDialog("client-dialog");

	cy.selectCountry("client-country-select", "France");
	cy.get('[name="address"]').clear().type("1 Rue du Test");
	cy.get('[name="postalCode"]').clear().type("75000");
	cy.get('[name="city"]').clear().type("Paris");
	cy.continueSteppedDialog("client-dialog");

	cy.get('[data-cy="client-identifier-LEGAL_ID"]', { timeout: 10000 }).clear().type("123456789");
	if (opts?.vat) {
		cy.get('[data-cy="client-identifier-VAT"]').clear().type(opts.vat);
	}
	cy.continueSteppedDialog("client-dialog");

	// ASCII-only slug — an accented character (e.g. "Confirmé") makes an otherwise-plausible email
	// fail the form's own RFC-ish check ("Email format is invalid"), which this mutation hit for real.
	const emailSlug = name
		.normalize("NFD")
		.replace(/[\u0300-\u036f]/g, "")
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-");
	cy.get('[name="contactEmail"]')
		.clear()
		.type(`${emailSlug}@example.com`);
	cy.continueSteppedDialog("client-dialog");

	cy.get('[data-cy="client-submit"]').click();
	cy.get('[data-cy="client-dialog"]').should("not.exist");
}

describe("Receiving invoices", () => {
	before(() => {
		cy.resetAndSeed();
	});

	beforeEach(() => {
		cy.login();
		cy.visit("/documents/received-invoice");
	});

	it("uploading a Factur-X: the extracted fields pre-fill the form, confirming creates a 'received' document, and the original downloads identically", () => {
		uploadAndOpenForm(FACTURX_FIXTURE);

		// Every received-invoice field is optional, so the wizard opens directly on "Lines" (no
		// "Details" step exists — document-create-dialog.tsx's own `buildFieldGroups`). The line
		// (BG-25) embedded in this same CII is extracted and pre-filled without retyping; its sum
		// (3 x 250.00 @ 20% = 900.00 gross) agrees EXACTLY with the totals deposited below, so NO
		// warning should appear — the regression this test genuinely covers, on a well-formed document.
		cy.get('input[name="lines.0.description"]').should("have.value", "Prestation fixture");
		cy.get('input[name="lines.0.quantity"]').should("have.value", "3");
		cy.get('input[name="lines.0.unitPrice"]').should("have.value", "250");
		cy.get('input[name="lines.0.vatRate"]').should("have.value", "20");
		cy.get('[data-cy="document-line-total-warnings"]').should("not.exist");
		cy.continueDocumentWizard(); // Lines -> Options

		cy.get('[data-cy="document-field-supplier-input"]').should(
			"have.value",
			"Fixture Fournisseur SARL",
		);
		cy.get('[data-cy="document-field-supplierNumber-input"]').should("have.value", "FIXTURE-INV-0001");
		cy.get('[data-cy="document-field-netAmount-input"]').should("have.value", "750");
		cy.get('[data-cy="document-field-vatAmount-input"]').should("have.value", "150");
		cy.get('[data-cy="document-field-grossAmount-input"]').should("have.value", "900");
		// The currency selector shows EUR, and the date picker is no longer on its placeholder —
		// both prove the pre-fill without depending on the exact format of their own internal rendering.
		cy.get('[data-cy="document-field-currency-input"]').should("contain.text", "EUR");
		cy.get('[data-cy="document-field-issueDate-input"]').should("not.contain.text", "Pick a date");

		confirmReceive();

		// Back to the list, badge visible.
		cy.get('[data-cy="document-list-cards"]', { timeout: 10000 })
			.contains("Fixture Fournisseur SARL")
			.closest('[data-cy^="document-list-row-"]')
			.find('[data-cy="document-status-badge"]')
			.should("contain.text", "Received");

		listReceivedInvoices().then((instances) => {
			const created = instances.find((i) => i.data.supplier === "Fixture Fournisseur SARL");
			expect(created, "le document créé est bien retrouvé par l'API").to.exist;
			expect(created?.status).to.eq("received");
			expect(created?.data.fileRef, "un fileRef a été attaché").to.be.a("string");
			expect(
				created?.data.lineTotalWarnings,
				"pas d'écart, donc pas d'avertissement — même quand la ligne EST là",
			).to.deep.equal([]);

			// The download button exists on screen…
			cy.get(`[data-cy="document-custom-received-invoice-download-button-${created!.id}"]`, {
				timeout: 10000,
			}).should("be.visible");

			// … and the API serves exactly the uploaded bytes (a content assertion, never the screen —
			// window.open() opens a tab that Cypress does not observe).
			cy.readFile(FACTURX_FIXTURE, "binary").then((original) => {
				cy.request({
					url: `${api}/api/documents/received-invoices/${created!.id}/file`,
					encoding: "binary",
				}).then((res) => {
					expect(res.status).to.eq(200);
					expect(res.body).to.eq(original);
				});
			});
		});
	});

	it("uploading a CII XML then approving through the screen moves the document to 'approved'", () => {
		uploadAndOpenForm(CII_FIXTURE);
		confirmReceive();

		listReceivedInvoices().then((instances) => {
			// The most recent (sorted by updatedAt desc — persistence.ts) is the one just created.
			const created = instances[0];
			expect(created.data.supplier).to.eq("Fixture Fournisseur SARL");
			const id = created.id;

			cy.runDocumentRowAction(id, "approve");
			cy.get('[data-sonner-toast]', { timeout: 10000 }).should("exist");

			cy.get(`[data-cy="document-list-row-${id}"]`)
				.find('[data-cy="document-status-badge"]')
				.should("contain.text", "Approved");

			cy.request<ReceivedInvoiceInstance>({ url: `${api}/api/documents/${id}?typeId=received-invoice` })
				.its("body")
				.its("status")
				.should("eq", "approved");
		});
	});

	it("a plain PDF (no embedded XML): empty form but the file is still attached, never a refusal", () => {
		uploadAndOpenForm(PLAIN_PDF_FIXTURE);

		// The screen STATES the absence of an OCR extractor, never a silence: TODAY's
		// behavior (empty form, manual entry) stays unchanged, PROVEN
		// preserved by the three empty-field assertions right below.
		cy.get('[data-sonner-toast]', { timeout: 10000 }).should("contain.text", "OCR");

		// No line was extracted from this PDF either — "Lines" (the wizard's own first step; see the
		// previous test's comment) shows no row, nothing to check there. "supplier" etc. are on
		// "Options", one step later.
		cy.continueDocumentWizard(); // Lines -> Options
		cy.get('[data-cy="document-field-supplier-input"]').should("have.value", "");
		cy.get('[data-cy="document-field-supplierNumber-input"]').should("have.value", "");
		cy.get('[data-cy="document-field-netAmount-input"]').should("have.value", "");

		confirmReceive();

		listReceivedInvoices().then((instances) => {
			const created = instances[0]; // the most recent
			expect(created.data.supplier, "aucun fournisseur extrait de ce PDF pur").to.be.oneOf([
				undefined,
				"",
			]);
			expect(created.status).to.eq("received");
			expect(created.data.fileRef, "le fichier est attaché malgré l'absence d'extraction").to.be.a(
				"string",
			);
			expect(
				created.data.lineTotalWarnings,
				"aucune ligne lisible : rien à contrôler, jamais un avertissement",
			).to.deep.equal([]);

			cy.readFile(PLAIN_PDF_FIXTURE, "binary").then((original) => {
				cy.request({
					url: `${api}/api/documents/received-invoices/${created.id}/file`,
					encoding: "binary",
				}).then((res) => {
					expect(res.status).to.eq(200);
					expect(res.body).to.eq(original);
				});
			});
		});
	});

	// The "extractor available" counterpart of the previous test: a PDF marked
	// for the test OCR stub arrives PRE-FILLED, but stays EDITABLE (a proposal, never a
	// truth — the human validates); supplier matching and the sum check
	// then run on the SAME fields, exactly as for a structural extraction.
	it("A PDF marked for the test OCR stub arrives pre-filled via OCR, and stays editable", () => {
		uploadAndOpenForm(OCR_FAKE_FIXTURE);

		cy.get('[data-sonner-toast]', { timeout: 10000 }).should("contain.text", "OCR");

		// "Lines" (the wizard's own first step) first, then "Options" for the rest.
		cy.get('input[name="lines.0.description"]').should("have.value", "OCR Fake Line");
		cy.get('input[name="lines.0.quantity"]').should("have.value", "1");
		cy.get('input[name="lines.0.unitPrice"]').should("have.value", "500");
		cy.continueDocumentWizard(); // Lines -> Options

		cy.get('[data-cy="document-field-supplier-input"]').should("have.value", "OCR Fake Fournisseur SARL");
		cy.get('[data-cy="document-field-supplierNumber-input"]').should("have.value", "OCR-FAKE-0001");
		cy.get('[data-cy="document-field-netAmount-input"]').should("have.value", "500");
		cy.get('[data-cy="document-field-vatAmount-input"]').should("have.value", "100");
		cy.get('[data-cy="document-field-grossAmount-input"]').should("have.value", "600");

		// EDITABLE — never frozen: the human corrects the pre-filled name before confirming.
		cy.get('[data-cy="document-field-supplier-input"]')
			.clear()
			.type("Corrigé Par Humain SARL");

		confirmReceive();

		listReceivedInvoices().then((instances) => {
			const created = instances.find((i) => i.data.supplier === "Corrigé Par Humain SARL");
			expect(created, "l'édition humaine du champ pré-rempli par OCR est bien celle enregistrée").to
				.exist;
			expect(created?.status).to.eq("received");
		});
	});

	it("Structured deposit with lines: the lines display without retyping, and a total/lines mismatch shows a named warning, never blocking", () => {
		uploadAndOpenForm(MISMATCH_FIXTURE);

		// The line (description, quantity, unit price excl. VAT, VAT rate) is pre-filled by
		// the extraction — never retyped. By NAME, not by data-cy — same convention as spec 20
		// (20-document-totals.cy.ts): a line sub-field's data-cy is shared across lines,
		// only the react-hook-form `name` (`lines.0.xxx`) is unique.
		cy.get('[data-cy="document-field-lines-row-0"]').should("exist");
		cy.get('input[name="lines.0.description"]').should("have.value", "Prestation désaccordée");
		cy.get('input[name="lines.0.quantity"]').should("have.value", "5");
		cy.get('input[name="lines.0.unitPrice"]').should("have.value", "100");
		cy.get('input[name="lines.0.vatRate"]').should("have.value", "20");
		cy.continueDocumentWizard(); // Lines -> Options ("grossAmount" lives there)

		// The deposited gross total (650) is carried over AS-IS — never rewritten by the sum of the lines (600).
		cy.get('[data-cy="document-field-grossAmount-input"]').should("have.value", "650");

		// The mismatch never prevents saving — the invoice remains savable as-is.
		confirmReceive();

		listReceivedInvoices().then((instances) => {
			const created = instances.find(
				(i) => i.data.supplier === "Fixture Fournisseur Discordant SARL",
			);
			expect(created, "le document créé malgré l'écart est bien retrouvé par l'API").to.exist;
			expect(created?.status).to.eq("received");

			const warnings = created?.data.lineTotalWarnings as string[];
			expect(warnings, "un avertissement NOMMÉ est porté par le document").to.have.length(1);
			expect(warnings[0]).to.match(/Line total mismatch \(gross \/ TTC\)/);

			// … and it is VISIBLE ON SCREEN when reopening the document from the list (not only at
			// creation time — the document CARRIES it).
			cy.openDocument(created!.id);
			// The dialog itself IS visible; the warning banner sits below the lines field, past the
			// fold of the dialog's own scrollable content — scrollIntoView() is what genuinely proves
			// "visible on screen" for an element a real reviewer would just scroll down to see, rather
			// than a `.should('exist')` that would also pass for something CSS actually hid.
			cy.get('[data-cy="document-line-total-warnings"]', { timeout: 10000 })
				.scrollIntoView()
				.should("be.visible")
				.and("contain.text", "gross / TTC");
		});
	});

	it("Editing a line makes the sum check react (the number of warnings changes)", () => {
		listReceivedInvoices().then((instances) => {
			const target = instances.find((i) => i.data.supplier === "Fixture Fournisseur Discordant SARL");
			expect(target, "le document créé par le test précédent existe toujours").to.exist;

			cy.openDocument(target!.id);

			// Before editing: a single warning (gross/TTC — see the previous test).
			cy.get('[data-cy="document-line-total-warnings"] p').should("have.length", 1);

			// The quantity is doubled (5 -> 10): the line becomes net 1000 / VAT 200 / gross 1200, which
			// no longer agrees with ANY of the three deposited totals (500 / 100 / 650) — the three
			// warnings must appear, the proof that the check REACTS to editing a line.
			cy.get('input[name="lines.0.quantity"]').clear({ force: true }).type("10", { force: true });
			cy.runDocumentAction("receive");
			cy.get('[data-sonner-toast]', { timeout: 10000 }).should("exist");

			// The record's page stays where it is after a successful "receive" on an already-existing
			// record (document-detail.tsx adopts the response as the form's new baseline): the banner,
			// ON SCREEN, must therefore already show the THREE warnings without reopening the document.
			cy.get('[data-cy="document-line-total-warnings"] p', { timeout: 10000 }).should("have.length", 3);

			cy.request<ReceivedInvoiceInstance>({
				url: `${api}/api/documents/${target!.id}?typeId=received-invoice`,
			})
				.its("body")
				.then((updated) => {
					const warnings = updated.data.lineTotalWarnings as string[];
					expect(warnings, "l'édition de la ligne a fait réagir le contrôle").to.have.length(3);
					expect(warnings.some((w) => w.includes("net / HT"))).to.eq(true);
					expect(warnings.some((w) => w.includes("VAT"))).to.eq(true);
					expect(warnings.some((w) => w.includes("gross / TTC"))).to.eq(true);
				});
		});
	});

	it("An existing client carrying the seller's VAT, created THROUGH THE SCREEN, links automatically to the deposit", () => {
		createClientByScreen("Fournisseur Confirmé SARL", { vat: SUPPLIER_VAT });

		cy.visit("/documents/received-invoice");
		uploadAndOpenForm(KNOWN_VAT_FIXTURE);
		// "supplierClient"/"supplier" are on "Options", one step past the wizard's own first step
		// ("Lines" — this fixture's own line isn't read by this test).
		cy.continueDocumentWizard(); // Lines -> Options

		// Visible BEFORE even confirming: the reference field already shows the resolved client — the
		// same generic pre-fill as any other extracted field (buildInitialData).
		cy.get('[data-cy="document-field-supplierClient-input"]', { timeout: 10000 }).should(
			"contain.text",
			"Fournisseur Confirmé SARL",
		);
		// The FREE-TEXT name (the seller's own name on THEIR OWN invoice) stays independent of the link.
		cy.get('[data-cy="document-field-supplier-input"]').should(
			"have.value",
			"Fixture Fournisseur Reconnu SARL",
		);

		confirmReceive();

		listReceivedInvoices().then((instances) => {
			const created = instances.find((i) => i.data.supplier === "Fixture Fournisseur Reconnu SARL");
			expect(created, "le document créé est bien retrouvé par l'API").to.exist;
			expect(created?.data.supplierClient, "le lien auto est bien persisté").to.be.a("string");

			cy.request<{ id: string; isSupplier?: boolean }[]>({
				url: `${api}/api/clients/search?query=${encodeURIComponent("Fournisseur Confirmé SARL")}`,
			}).then((res) => {
				const client = res.body[0];
				expect(client, "le client créé par l'écran est bien retrouvé par l'API").to.exist;
				expect(client.id).to.eq(created?.data.supplierClient);
				expect(client.isSupplier, "le rôle supplier est posé au moment du lien (auto)").to.eq(true);
			});
		});
	});

	it("A deposit from an UNKNOWN seller links nothing, and the screen says so", () => {
		uploadAndOpenForm(UNKNOWN_VAT_FIXTURE);
		cy.continueDocumentWizard(); // Lines -> Options ("supplierClient" lives there)

		// The field stays empty — never a guessed link.
		cy.get('[data-cy="document-field-supplierClient-input"]').should(
			"not.contain.text",
			"Fournisseur",
		);
		// … and the screen says so: a NAMED message, not a silence.
		cy.get('[data-sonner-toast]', { timeout: 10000 }).should("contain.text", "No matching supplier");

		confirmReceive();

		listReceivedInvoices().then((instances) => {
			const created = instances.find((i) => i.data.supplier === "Fixture Fournisseur Inconnu SARL");
			expect(created, "le document créé malgré l'absence de lien est bien retrouvé").to.exist;
			expect(created?.data.supplierClient, "aucun lien deviné, jamais un fournisseur créé en douce").to.be
				.oneOf([undefined, ""]);
		});
	});

	it("Linking a supplier BY HAND sets the 'supplier' role, visible on the clients side", () => {
		createClientByScreen("Fournisseur Manuel SARL");

		cy.visit("/documents/received-invoice");
		listReceivedInvoices().then((instances) => {
			const target = instances.find((i) => i.data.supplier === "Fixture Fournisseur Inconnu SARL");
			expect(target, "le document 'vendeur inconnu' du test précédent existe toujours").to.exist;

			cy.openDocument(target!.id);

			cy.get('[data-cy="document-field-supplierClient-input"] button').first().click({ force: true });
			cy.get('[data-cy="document-field-supplierClient-input-options"]', { timeout: 10000 }).should(
				"be.visible",
			);
			cy.get('[data-cy="document-field-supplierClient-input"] input').type("Fournisseur Manuel SARL");
			cy.get(
				'[data-cy="document-field-supplierClient-input-option-fournisseur-manuel-sarl"]',
				{ timeout: 10000 },
			).click();

			cy.runDocumentAction("receive");
			cy.get('[data-sonner-toast]', { timeout: 10000 }).should("exist");

			cy.request<ReceivedInvoiceInstance>({
				url: `${api}/api/documents/${target!.id}?typeId=received-invoice`,
			})
				.its("body")
				.then((updated) => {
					expect(updated.data.supplierClient, "le lien MANUEL est bien persisté").to.be.a("string");

					cy.request<{ id: string; isSupplier?: boolean }[]>({
						url: `${api}/api/clients/search?query=${encodeURIComponent("Fournisseur Manuel SARL")}`,
					}).then((res) => {
						const client = res.body[0];
						expect(client.id).to.eq(updated.data.supplierClient);
						expect(
							client.isSupplier,
							"visible côté clients : le rôle supplier est posé même pour un lien MANUEL",
						).to.eq(true);
					});
				});
		});
	});

	it("the same file re-uploaded (same hash — the CII XML already received above) is refused, named, as a duplicate", () => {
		// The previous test ends on a record's own page; the upload button is the LIST's.
		cy.visit("/documents/received-invoice");
		cy.get('[data-cy="received-invoice-upload-button"]', { timeout: 15000 }).click();
		cy.get('[data-cy="received-invoice-upload-file-input"]').selectFile(CII_FIXTURE, { force: true });
		cy.get('[data-sonner-toast]', { timeout: 10000 }).should("contain.text", "duplicate");
		// Refused at the upload stage: no creation form appears.
		cy.get('[data-cy="document-form"]').should("not.exist");
	});

	// The 2026-09-17 multipart/form-data decision: an 11 MB deposit is aborted by multer's own
	// `limits.fileSize` (received-invoices.controller.ts's `upload`) at the wire itself, a real 413,
	// BEFORE `ReceivedInvoicesService.upload` — and therefore `persistInboundFile` — ever runs. The
	// intercepted response code is the proof no partial write is even attempted; the API listing
	// afterward is the proof no document was created either.
	it("an oversized deposit (11 MB) is refused with a 413, before a single byte reaches disk", () => {
		cy.visit("/documents/received-invoice");
		cy.get('[data-cy="received-invoice-upload-button"]', { timeout: 15000 }).click();
		cy.get('[data-cy="received-invoice-upload-dialog"]', { timeout: 10000 }).should("be.visible");

		cy.intercept("POST", `${api}/api/documents/received-invoices/upload`).as("uploadReceivedInvoice");
		cy.get('[data-cy="received-invoice-upload-file-input"]').selectFile(
			{
				contents: Cypress.Buffer.concat([
					Cypress.Buffer.from("%PDF-1.4\n"),
					Cypress.Buffer.alloc(11 * 1024 * 1024, 0x20),
				]),
				fileName: "oversized-scan.pdf",
				mimeType: "application/pdf",
			},
			{ force: true },
		);
		cy.wait("@uploadReceivedInvoice").its("response.statusCode").should("eq", 413);

		cy.get('[data-sonner-toast]', { timeout: 15000 }).should("contain.text", "10 MB");
		// Refused at the upload stage: no creation form appears.
		cy.get('[data-cy="document-form"]').should("not.exist");

		listReceivedInvoices().then((instances) => {
			expect(
				instances.find((i) => i.data.fileName === "oversized-scan.pdf"),
				"un dépôt refusé au niveau multipart ne crée jamais de document",
			).to.be.undefined;
		});
	});

	it("regression 17: 'received-invoice' appears in the list of registered types", () => {
		cy.request<{ id: string; label: string }[]>({ url: `${api}/api/documents/types` })
			.its("body")
			.then((types) => {
				expect(types.map((t) => t.id)).to.include("received-invoice");
			});
	});

	it("regression 11: the dashboard always shows at least one contribution, none unrendered", () => {
		cy.visit("/dashboard");
		cy.get('[data-cy^="widget-"]', { timeout: 20000 }).should("exist");
		cy.get('[data-cy="widget-unsupported"]').should("not.exist");
	});
});
