{{- if and (not .Values.redis.external.host) .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "invoicerr.componentFullname" (dict "context" . "component" "redis") }}
  labels:
    {{- include "invoicerr.componentLabels" (dict "context" . "component" "redis") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.redis.persistence.storageClassName }}
  storageClassName: {{ .Values.redis.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}
