import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * One sidebar per top-level navbar section, so navigating to a section (User Guide, Developer
 * Guide, ...) only shows that section's pages, instead of the whole docs tree. Getting-started
 * content (introduction, installation) lives inside the User Guide sidebar (`docs/user-guide/`)
 * rather than as its own section — four sections total, matching the navbar: User Guide,
 * Developer Guide, Legal, and Compliance (the latter is not a `docs`-plugin sidebar at all: its
 * per-country pages are generated by `plugins/compliance-content-plugin.ts` from
 * `compliance/<CC>-<Country>.md` and listed on the `/compliance` index page instead).
 */
const sidebars: SidebarsConfig = {
  developerGuideSidebar: [
    {type: 'autogenerated', dirName: 'developer-guide'},
  ],
  userGuideSidebar: [
    {type: 'autogenerated', dirName: 'user-guide'},
  ],
  // Terms of Service, Privacy Policy, Data Processing Agreement, Legal Notice, Cookies & Acceptable
  // Use — `docs/legal/`, ordered by each file's own `sidebar_position` front matter (1-5, see each
  // file). Added 2026-09-16 alongside the four new documents and the in-app acceptance flow
  // (`backend/src/legal/`, `frontend/src/pages/legal/`) — before this, `terms-of-service.md` built as
  // a page but was reachable only by direct URL, in no sidebar and no navbar entry.
  legalSidebar: [
    {type: 'autogenerated', dirName: 'legal'},
  ],
};

export default sidebars;
