import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * One sidebar per top-level navbar section, so navigating to a section (User Guide, Developer
 * Guide, ...) only shows that section's pages, instead of the whole docs tree. Getting-started
 * content (introduction, installation) lives inside the User Guide sidebar (`docs/user-guide/`)
 * rather than as its own section — three sections total, matching the navbar: User Guide,
 * Developer Guide, and Compliance (the latter is not a `docs`-plugin sidebar at all: its per-country
 * pages are generated by `plugins/compliance-content-plugin.ts` from `compliance/<CC>-<Country>.md`
 * and listed on the `/compliance` index page instead).
 */
const sidebars: SidebarsConfig = {
  developerGuideSidebar: [
    {type: 'autogenerated', dirName: 'developer-guide'},
  ],
  userGuideSidebar: [
    {type: 'autogenerated', dirName: 'user-guide'},
  ],
};

export default sidebars;
