import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * One sidebar per top-level navbar section, so navigating to a section
 * (Getting Started, Developer Guide, ...) only shows that section's pages,
 * instead of the whole docs tree.
 */
const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [
    {type: 'autogenerated', dirName: 'getting-started'},
  ],
  developerGuideSidebar: [
    {type: 'autogenerated', dirName: 'developer-guide'},
  ],
  apiReferenceSidebar: [
    {type: 'autogenerated', dirName: 'api-reference'},
  ],
  changelogSidebar: ['changelog'],
};

export default sidebars;
